config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shirts
  root "shirts#index"  
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
	belongs_to :user	

	has_attached_file :image, styles: { medium: "300x300>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :shirts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
	before_action :find_shirt, only: [:show, :edit, :update, :destroy]

	def index
		@shirts = Shirt.all.order("created_at DESC")
	end 

	def new
		@shirt = current_user.shirts.build
	end

	def create


		@shirt = current_user.shirts.build(shirt_params)

		if @shirt.save
			redirect_to @shirt, notice: "Succesfully created"
		else
			render 'new'
		end

	end 

	def show 	
	end

	def edit
	end

	def update
		if @shirt.update(shirt_params)
			redirect_to @shirt, notice: "Shirt was succesfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@shirt.destroy
		redirect_to root_path
	end




	private

	def shirt_params
		params.require(:shirt).permit(:name, :price, :image)
	end

	def find_shirt
		@shirt = Shirt.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default

		.container
			.navbar-brand= link_to "Levite Board", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Shirt", new_shirt_path
					%li= link_to "Account Settings", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			-else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign up", new_user_registration_path
					%li= link_to "Sign in", new_user_session_path

	.container	
		-flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
		= yield

app/views/shirts/_form.html.haml
= simple_form_for @shirt, html: {multipart: true} do |f|
	- if @shirt.errors.any?
		#errors 
			%h2
			= pluralize(@shirt.errors.count, "error")
			prevented this Shirt from saving
			%ul
				- @shirt.errors.full_messages.each do |msg|
					%li =msg


	.form-group
		= f.input :image, input_html: {class: 'form-control'}
	
	.form-group
		= f.input :name, input_html: {class: 'form-control'}

	.form-group
		= f.input :price, input_html: {class: 'form-control'}

	= f.button :submit, class: "btn btn-primary"

app/views/shirts/edit.html.haml
.col-md-6.col-md-offset-3
	
	%h1 Edit Pin
	= image_tag @shirt.image.url(:medium)
	= render 'form'

	= link_to "Cancel", shirt_path

app/views/shirts/index.html.haml
#shirts.transitions-enabled
	- @shirts.each do |shirt|
		.box.panel.panel-default
			= link_to (image_tag shirt.image.url(:medium)), shirt
			.panel-body
				%h2= link_to shirt.name, shirt
				%p= shirt.price

app/views/shirts/new.html.haml
.col-md-6.col-md-offset-3

	%h1 New Shirt

	= render 'form'

	= link_to "Back", root_path

app/views/shirts/show.html.haml
= image_tag @shirt.image.url(:medium)
%h1= @shirt.name
%p= @shirt.price

%br/

= link_to "Back", root_path
= link_to "Edit", edit_shirt_path
= link_to "Delete", shirt_path, method: :delete, data: {confirm: "Are you sure"}